app/models.py
from flask_admin.contrib.sqla.view import ModelView
from sqlalchemy.orm import backref
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime
from flask_login import current_user
from flask import render_template, request, redirect, url_for
from flask_security import RoleMixin







roles_users = db.Table('roles_users',
    db.Column('user_id', db.Integer, db.ForeignKey('users.id')),
    db.Column('role_id', db.Integer, db.ForeignKey('roles.id')))
#callback function to retrieve a user when a unique identifier is passed 
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin, db.Model):
    __tablename__= 'users'
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(255), index = True)
    email = db.Column(db.String(255), unique = True, index = True)
    passcode = db.Column(db.String(255))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    active = db.Column(db.Boolean)
    confirmed_at = db.Column(db.DateTime)

    roles = db.relationship('Role', secondary=roles_users, backref='users', lazy='dynamic')




    

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')
    @password.setter
    def password(self, password):
        self.passcode = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.passcode, password)

    def is_active(self):
        return self.active

    def __repr__(self):
        return f'User {self.username}'


#api endpoint class

class Quote_Body:

    randomQuote = []

    def __init__(self, quote, author, permalink):
        self.quote = quote
        self.author = author
        self.permalink = permalink

# Role

class Role(db.Model, RoleMixin):
    __tablename__ = 'roles'

    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(255))
    description = db.Column(db.String(255))

    def __repr__(self):
        return f'User {self.name}'
 
 # new blog
class NewBlog(db.Model):
    __tablename__ = "blog"

    id = db.Column(db.Integer, primary_key = True)
    blogtitle = db.Column(db.String)
    myblog = db.Column(db.String)
    author = db.Column(db.String(255))
    postdate = db.Column(db.DateTime, default=datetime.utcnow)
    comments_blog = db.Column(db.String, db.ForeignKey('comments.comment'))

    def save_blog(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_blog(cls, id):
        userblogs = NewBlog.query.filter_by(blog_id=id).all()
        return userblogs

class Vote(db.Model):
    __tablename__ = "votes"

    id = db.Column(db.Integer, primary_key = True)
    

    def __repr__(self):
        return f'User {self.id}'

class Comments(db.Model):
    __tablename__= 'comments'
    id = db.Column(db.Integer)
    comment = db.Column(db.String, primary_key=True)

    blog = db.relationship('NewBlog',backref = 'comments',lazy="dynamic")


class MyModelView(ModelView):
    # def is_accessible(self):
    #     return current_user.is_authenticated

    # def inaccessible_callback(self, name, **kwargs):
    #     return redirect(url_for('main.index'))
    pass

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, TextAreaField
from wtforms import validators
from wtforms.fields.core import RadioField
from wtforms.validators import Required

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us a little about yourself', validators = [Required()])
    submit = SubmitField('Submit')


class BlogForm(FlaskForm):

    title = StringField('Pitch title', validators=[Required()])
    name = TextAreaField('Pitch', validators=[Required()])
    author = StringField('Author : ', validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from flask import Flask
from config import config_options
from flask_login import LoginManager
from flask_mail import Mail
from flask_simplemde import SimpleMDE
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_admin import Admin, BaseView



login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
mail = Mail()
simple = SimpleMDE()


#Uploading Images
photos = UploadSet('photos', IMAGES)

def create_app(config_name):
    # Initializing application
    app = Flask(__name__,template_folder='templates', static_folder='static')

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)

    # Initalizing database
    db.init_app(app)

    #Initializing Admin

 

    
    

    # Initializing login manager
    login_manager.init_app(app)

    # Initializing mail
    mail.init_app(app)

    #initializing simple review editor
    simple.init_app(app)

    # configuring uploadset
    configure_uploads(app, photos)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix = '/authenticate')

    # setting config
    # from .requests import configure_request
    # configure_request(app)

    return app

app/main/__init__.py
from flask import Blueprint, Flask

main = Blueprint('main',__name__)
from . import views, errors

app/main/views.py
from flask import render_template, request, redirect, url_for, abort
from . import main
from ..requests import get_quotes, get_quotes1, get_quotes2, get_quotes3, get_quotes4
from flask_login import login_required, current_user
from app.models import User, NewBlog
from . forms import UpdateProfile, BlogForm
from app import db, photos
from flask_admin import BaseView, expose
from flask_admin.contrib.sqla import ModelView


@main.route('/')
def index():
    '''
    View root page function that returns the index page and its data
    '''
    title="Le Blunt"
    randomquotes = get_quotes()
    randomquotes1 = get_quotes1()
    randomquotes2 = get_quotes2()
    randomquotes3 = get_quotes3()
    randomquotes4 = get_quotes4()

    return render_template('index.html', title=title, randomquotes = randomquotes, randomquotes1=randomquotes1, randomquotes2=randomquotes2, randomquotes3=randomquotes3, randomquotes4=randomquotes4)

@main.route('/userblogpage', methods = ['GET', 'POST'])
@login_required
def userblogpage():
    '''
    View userpage page function that returns the userpage page and its data
    ''' 

    blog_body = NewBlog.query.all()

    return render_template('userblogpage.html', blog_body=blog_body)

#Display profile
@main.route('/user/<uname>')
def profile(uname):

    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

#Update Profile

@main.route('/user/<uname>/update', methods = ['GET', 'POST'])
@login_required
def updateprofile(uname):

    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile', uname=user.username))

    return render_template("profile/update.html", form = form)


@main.route('/user/<uname>/update/pic', methods=['POST'])
@login_required
def updateppic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:

        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()

    return redirect(url_for('main.profile', uname=uname))


# Blog form

@main.route('/createblog', methods = ['GET', 'POST'])
@login_required
def createblog():
    '''
    View userpage page function that returns the userpage page and its data
    ''' 
    form = BlogForm() 
    if form.validate_on_submit():


        upblog = NewBlog( blogtitle = form.title.data, myblog = form.name.data, author = form.author.data)

        db.session.add(upblog)
        db.session.commit()

        return redirect(url_for('main.userblogpage'))

    return render_template('createblog.html', blog_form = form)



@expose('/admin', methods=['GET', 'POST'])
def administrator():
    blog_body = NewBlog.query.all()

    return render_template('userblogpage.html', blog_body=blog_body)

app/templates/base.html
{% extends 'bootstrap/base.html' %}
<!DOCTYPE html>
<html lang="en" {% block html_attribs %}{% endblock html_attribs %}>
<head>
    {%- block head %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Le Blunt</title>
    {%- block meta %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% endblock %}
    {%block styles %}
    {{super()}}
    <!--Importing the simple mde css and js files  -->
    {{ simplemde.css}}
    {{ simplemde.js }}

    {% endblock %}
    {% endblock%}
    {% block content %}
    {% endblock %}
    {% block scripts %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    {% endblock %}

</head>
<body {% block body_attribs %}{% endblock body_attribs %}>
    {% block navbar %}
        {% include 'navbar.html' %}
    {% endblock %}

</body>
</html>

app/templates/createblog.html
    {% extends 'base.html' %}
    {% import 'bootstrap/wtf.html' as wtf %}
    {% block head %}
    <!-- css link -->
    {% block styles %}
    <!--bootstrap link-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {{ super() }}
    <link rel="stylesheet"  href="{{ url_for('static', filename='../static/css/userpage.css') }}">
    {% endblock %}
    <title>{{ title }}</title>
    {% endblock %}
    
    {% block content %}
    <!-- quote body starts here -->
    <div class="container-fluid">
        <div class="row col-sm-12 col-md-12 col-lg-12 my-3 mr-3">
            <div class="col-sm-4 col-md-4 col-lg-4 card mx-auto">
                {{ wtf.quick_form(blog_form) }}

            </div>
        </div>
    </div>
    {% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% block head %}
{% block styles %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
{{ super() }}
<link rel="stylesheet"  href="{{ url_for('static', filename='../static/css/index.css') }}">
{% endblock %}
<title>{{ title }}</title>
{% endblock %}

{% block content %}
<div class="container w-80">
    <!-- Carousel body -->
    <div id="carouselLightMode" class="carousel slide carousel-fade carousel-light pointer-event w-80 mx-auto" data-bs-ride="carousel">
        <!-- Indicators --> 
        <div class="carousel-indicators my-3">
            <button data-bs-target="#carouselLightMode" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button data-bs-target="#carouselLightMode" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button data-bs-target="#carouselLightMode" data-bs-slide-to="2" aria-label="Slide 3"></button>
            <button data-bs-target="#carouselLightMode" data-bs-slide-to="3" aria-label="Slide 4"></button>
            <button data-bs-target="#carouselLightMode" data-bs-slide-to="4" aria-label="Slide 5"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item overlay active">
                <img src="../static/photos/sunrise.jpg" class="d-block w-100 pic" alt="different times of the day" height="600px">
                <div class="carousel-caption  d-none d-md-block p-4" style="background-color:rgba(226, 225, 225, 0.5); color:black; transform: translate(-50%, -50%); position: absolute; top: 50%; left: 50%;-webkit-transform: translate(-50%, -50%); width:70%; height:60%">
                    <h1>{{randomquotes.quote}}</h1>
                    <p>{{randomquotes.author}}</p>
                    <a href="{{randomquotes.permalink}}" class="btn btn-dark">Read More</a>

                </div>
            </div>
            <div class="carousel-item overlay">
                <img src="../static/photos/aztec.jpg" class="d-block w-100 pic" alt="different times of the day" height="600px">
                <div class="carousel-caption d-none d-md-block p-4" style="background-color:rgba(226, 225, 225, 0.5); color:black; transform: translate(-50%, -50%); position: absolute; top: 50%; left: 50%;-webkit-transform: translate(-50%, -50%); width:70%; height:60%;">
                    <h1>{{randomquotes1.quote}}</h1>
                    <p>{{randomquotes1.author}}</p>
                    <a href="{{randomquotes1.permalink}}" class="btn btn-dark">Read More</a>
                </div>
            </div>
            <div class="carousel-item overlay">
                <img src="../static/photos/trees.jpg" class="d-block w-100 pic" alt="different times of the day" height="600px">
                <div class="carousel-caption d-none d-md-block p-4" style="background-color:rgba(226, 225, 225, 0.5); color:black; transform: translate(-50%, -50%); position: absolute; top: 50%; left: 50%;-webkit-transform: translate(-50%, -50%); width:70%; height:60%;">
                    <h1>{{randomquotes2.quote}}</h1>
                    <p>{{randomquotes2.author}}</p>
                    <a href="{{randomquotes2.permalink}}" class="btn btn-dark">Read More</a>
                </div>
            </div>
            <div class="carousel-item overlay">
                <img src="../static/photos/AthensGreece.jpg" class="d-block w-100 pic" alt="different times of the day" height="600px">
                <div class="carousel-caption d-none d-md-block p-4" style="background-color:rgba(226, 225, 225, 0.5); color:black; transform: translate(-50%, -50%); position: absolute; top: 50%; left: 50%;-webkit-transform: translate(-50%, -50%); width:70%; height:60%;">
                    <h1>{{randomquotes3.quote}}</h1>
                    <p>{{randomquotes3.author}}</p>
                    <a href="{{randomquotes3.permalink}}" class="btn btn-dark">Read More</a>
                </div>
            </div>
            <div class="carousel-item">
                <img src="../static/photos/china.png" class="d-block w-100 pic" alt="different times of the day" height="600px">
                <div class="carousel-caption d-none d-md-block p-4" style="background-color:rgba(226, 225, 225, 0.5); color:black; transform: translate(-50%, -50%); position: absolute; top: 50%; left: 50%;-webkit-transform: translate(-50%, -50%); width:70%; height:60%;">
                    <h1>{{randomquotes4.quote}}</h1>
                    <p>{{randomquotes4.author}}</p>
                    <a href="{{randomquotes4.permalink}}" class="btn btn-dark">Read More</a>
                </div>
            </div>
        </div>
        

        <button class="carousel-control-prev" type="button" data-bs-target="#carouselLightMode" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>

        <button class="carousel-control-next" type="button" data-bs-target="#carouselLightMode" data-bs-slide="prev">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</div>


{% endblock %}

app/templates/macros.html
{% macro displayBlog(blog_body) %}
<div class="container-fluid">
    <div class="row">
        <div class=" d-flex">
            {% for blogdata in blog_body %}
            <div class="col-xs-12 col-md-12 col-sm-12 col-lg-12 card ">
                <h4 class="text-center">{{ blogdata.blogtitle }}</h4>
                <hr>
                <p style="font-size:xx-large;">"</p>
                <h5>{{blogdata.myblog}}</h5>
                <hr>
                <div>
                    <p>Author : {{blogdata.author}}</p>
                    <div class="text-right">
                        <p class="">
                            <span class="btn btn-dark">👍 </span>0

                            <span class="btn btn-dark">👎  </span>0
                        </p>
                    </div>
                </div>
                <h4>Posted At : {{blogdata.postdate.strftime('%d/%m/%y')}}</h4>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endmacro %}

app/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>
</body>
{% block content %}
<div class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container-fluid d-inline">
        <a href="/" class="navbar-brand navbar-logo mt-0 mx-3">Le Blunt</a>
        <div class="collapse navbar-collapse" >
            <ul class="nav navbar-nav d-inline" >
                <li class="mx-3 d-block"><a href="/">Home</a></li>
                <li class="mx-3 d-block"><a href="/">About</a></li>
                <li class="mx-3 d-block"><a href="/">Contacts</a></li>
                {% if current_user.is_authenticated %}
                <li class="mx-3 d-block"><a href="{{url_for('main.userblogpage')}}">Blog</a></li>
                {% endif %}
            </ul>
            <div class="navbar navbar-nav navbar-right signlog d-inline">
                {% if current_user.is_authenticated %}
                <div class="d-flex">
                    <div class="my-auto mx-3 addblog">
                        <a href="{{url_for('main.createblog')}}" class="btn btn-primary "><i class="fa fa-plus"></i> Add Blog</a>
                    </div>
                    <div class="nav-item dropdown mx-3" >
                        <a href=""  class="nav-link dropdown-toggle user-action" data-bs-toggle="dropdown">
                            <img src="{{url_for('static', filename='user.profile_pic_path')}}" class="avatar" alt="Avatar">
                            <h5 class="d-inline">{{ current_user.username }} </h5>
                            <!-- <b class="caret"></b> -->
                        </a>
                        <div class="dropdown-menu" style="position:absolute !important;">
                            <a href="{{url_for('main.profile', uname=current_user.username)}}" class="dropdown-item">
                                <i class="fa fa-user-o"></i>
                                Profile
                            </a>
                            <a href="" class="dropdown-item">
                                <i class="fa fa-envelope"></i>
                                Messages
                            </a>
                            <div class="divider dropdown-divider"></div>
                            <a href="{{url_for('auth.logout')}}" class="dropdown-item">
                                <i class="fa fa-sign-out"></i>
                                Logout
                            </a>
                        </div>
                    </div>
                </div>
                {% else %}
                <div class="my-auto mx-3 signup d-inline">
                    <a href="{{url_for('auth.signup')}}" class="btn btn-success ">Sign Up</a>
                </div>
                <div class="my-auto mx-3 login d-inline">
                    <a href="{{url_for('auth.login')}}" class="btn btn-primary">
                        Log In
                    </a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}
</html>








<!-- <h4 class="d-inline">{{ current_user.username }} </h4>
<img src="../static/images/profile.png" alt="user ppic" height="50px" width="50px" class="d-inline">
<div class="my-auto mx-3 signout d-inline">
    <a href="{{url_for('main.profile', uname=current_user.username)}}" class="btn btn-primary ">View Profile</a>
</div>
<div class="my-auto mx-3 signout d-inline">
    <a href="{{url_for('auth.logout')}}" class="btn btn-primary ">Sign out</a>
</div> -->

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
    <div class="row">
        <!-- display Username -->
        <div class="col-md-4">
            <h3> {{ user.username | capitalize }}</h3>

            <!-- Displaying User Bio -->
            {% if user.bio %}
                <p> {{ user.bio }}</p>
            {% else %}
                <p> {{user.username | capitalize }} </p>
            {% endif %}
        </div>
        <div class="col-md-4">
        <!-- Display Profile Photo -->
        {% if user.profile_pic_path %}
            <img src="{{url_for('static', filename='user.profile_pic_path')}}" alt="ppic" class="img-thumbnail">
        {% else %}
            <p>No Profile Picture</p>
        {% endif %}
        </div>
        <!-- changeppic -->
        {% if user == current_user %}
        <form action="{{url_for('main.updateppic', uname=user.username)}}" method="post" enctype = "multipart/form-data">
            <input type="file" name="photo" class="form-control" required>
            <input type="submit">
        </form>
        {% endif %}
        {% if user == current_user %}
            <a href="{{url_for('main.updateprofile', uname=user.username)}}">Edit Profile</a>
        {% endif %}
    </div>
</div>

{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/userblogpage.html
{% extends 'base.html' %}

{% import 'bootstrap/wtf.html' as wtf %}
{% import 'macros.html' as macro %}

{% block head %}
<!-- css link -->
{% block styles %}
<!--bootstrap link-->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
{{ super() }}
<link rel="stylesheet"  href="{{ url_for('static', filename='../static/css/userpage.css') }}">
{% endblock %}
<title>{{ title }}</title>
{% endblock %}

{% block content %}
<!-- quote body starts here -->
<div class="container-fluid">
    <div class="row col-sm-12 col-md-12 col-lg-12 my-3 mr-3">
        {{macro.displayBlog(blog_body)}}
    </div>
</div>
{% endblock %}